version: "3"

services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: company
      MYSQL_USER: pradeep
      MYSQL_PASSWORD: pradeep
    ports:
      - 3306:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
      - ./database/DB.sql:/docker-entrypoint-initdb.d/DB.sql
    networks:
      - backendNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - backendNetwork
      - frontendNetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/company
      SPRING_DATASOURCE_USERNAME: pradeep
      SPRING_DATASOURCE_PASSWORD: pradeep

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 4200:80
    depends_on:
      - backend
    networks:
      - frontendNetwork
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf

volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork:
  frontendNetwork:
